### ISSUE TITLE
Unbonded CTL user withdraw contract failing

### ISSUE THREAD

**Issue by Michael-Hollister** [mlabs-haskell/singularitynet#109]
The user withdraw contract currently fails on either of these two conditions:
1. A user attempts to withdraw after the pool is closed (code needs to be updated since the state datum is now correctly withdrawn from the pool by the admin)
2. ~If multiple users withdraw from the pool, the contract will fail when the second user withdraws (this bug might also exist for the bonded contracts as well)~

**Comment by rmgaray** [comment]
The second issue described here no longer applies.

**Comment by rmgaray** [comment]
The reason the issue occurs is that the validator still validates the time of the user stake submission when, in fact, a user should be able to withdraw freely after the pool has been closed.
