### ISSUE TITLE
Loop sleep until script utxos change

### ISSUE THREAD

**Issue by vvtran** [mlabs-haskell/singularitynet#49]
All transactions should mutate the UTXO set at the validator address in some way e.g. the tx id will change, the datum, more UTXOs will appear. Instead of sleeping for 80 seconds, we can sleep for 1 second, looping over this until the UTXO set changes. This is probably sufficient for local testing but would go wrong if someone sends something to the validator of course.

An alternative method is to perhaps loop 1 second sleeps until the NFT UTXO has been found/updated. This won't work for user deposits though as the State NFT isn't always spent.

Open to suggestions on dynamic sleeping.

**Comment by rmgaray** [comment]
It seems to me that [this PR](https://github.com/Plutonomicon/cardano-transaction-lib/pull/741) in CTL will fix the issue. I'm currently adapting the bonded contracts to use `awaitTxConfirmed`.
